model = "gpt-5.2-codex"
model_reasoning_effort = "medium"

[features]
web_search_request = true
shell_snapshot = true

[env]
DISABLE_ZOXIDE = "1"

[projects."/Users/pedroapfilho/dev"]
trust_level = "trusted"

[projects."/Users/pedroapfilho/.codex"]
trust_level = "trusted"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
headers = { CONTEXT7_API_KEY = "CONTEXT7_API_KEY" }

[mcp_servers.chrome-devtools]
command = "cmd"
args = [
    "/c",
    "npx",
    "-y",
    "chrome-devtools-mcp@latest",
]
env = { SystemRoot="C:\\Windows", PROGRAMFILES="C:\\Program Files" }
startup_timeout_ms = 20_000

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
