[projects."/Users/pedroapfilho/dev/acme-monorepo"]
trust_level = "trusted"

[projects."/Users/pedroapfilho/dev/frow"]
trust_level = "trusted"

[projects."/Users/pedroapfilho/dev"]
trust_level = "trusted"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
headers = { CONTEXT7_API_KEY = "your-context7-api-key" }

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--extension"]

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp"
headers = { Authorization = "Bearer your-github-api-key" }

[mcp_servers.figma-dev-mode-mcp-server]
url = "http://127.0.0.1:3845/mcp"
